[build]
builder = "nixpacks"

[build.nixpacksConfig]
providers = ["node"]

[build.nixpacksConfig.node]
version = "20.11.0"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
NODE_ENV = "production"
PORT = "$PORT"

[environments.production.variables]
# Railway will automatically set PORT, but we can reference it